### PR TITLE
Added more languages, fixed Filipino

### PR DESCRIPTION
**Pull request by samhenrigold**
I've been using this for my portfolio landing page for a few months now, yesterday I got a [tweet](https://twitter.com/jkspn/status/1419119098630262784) suggesting a fix for the Filipino greeting string. Additional languages translated with Google, I'm planning to replace them with DeepL translations where I can.

English is removed since my site uses English as the default value and the JS just replaces it with translations.

### CODE REVIEW

**Comment by samhenrigold** [comment]
Babbel article used, pulled informal greetings: https://www.babbel.com/en/magazine/how-to-say-hello-in-10-different-languages

**Comment by AkshayHere** [comment]
Hi @novellac, Would really appreciate if you could merge this pull request to master.

**Comment by novellac** [comment]
Hi all,

Thanks for the nudge, I didn't see this earlier.

Thanks for the feedback about the Filipino translation. I'm happy you've gotten some use out of the list. I'd be happy to incorporate an update to the Filipino translation, but this PR removes some languages and makes some changes to others that I'm not comfortable with. While there may be better ways to greet someone in another language or context, I'd like to keep the repo narrowly focused; just a "hello" translated using Google translate from English to the target language. 

If you'd like to make a PR with just the Filipino translation, I'll happily accept that. If you don't have time, let me know and I'll commit it. If you decide to fork the repo to use DeepL, let me know, that sounds like a cool idea!

**Comment by samhenrigold** [comment]
Hey so sorry for the delay; would you mind committing just the Filipino version?

**Comment by novellac** [comment]
@samhenrigold - thanks again for the suggested fix for Filipino. I've made the commit [here](https://github.com/novellac/multilanguage-hello-json/commit/9bbdc38e86d5a0f719a0300269519348e556ad3b).

**Pull request closed without merging**
